# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [2]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [3]:
rand_array = np.random.random_sample((10, 10))
rand_range = 10*rand_array + 0        # random array of elements between 0  and 10
array_mean = np.mean(rand_range)
print ('Mean of array elements: {}'.format(array_mean))

Mean of array elements: 4.974067475232309


## Q2

Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [4]:
nrows = 5
ncols = 3
old_array = np.arange(1, 16, 1).reshape(ncols, nrows)
modified_array = old_array.T
new_array = modified_array[1:4:2, :]
print (new_array)

[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [5]:
nrows = 4
ncols = 5
array_1 = np.ones((nrows, ncols))
array_2 = array_1
array_2[1:nrows-1, 1:ncols-1] = 0
print (array_2)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [6]:
stride_val = 15
ang_array = np.arange(0, 90+stride_val, stride_val)
ang_array2 = (np.pi/180)*ang_array
sine_array = np.sin(ang_array2)
cosine_array = np.sin(ang_array2)
tangent_array = np.tan(ang_array2)
# Compute inverses
asin_array = np.arcsin(sine_array)
acos_array = np.arccos(cosine_array)
atan_array = np.arctan(tangent_array)

asin_array *= (180/np.pi)
acos_array *= (180/np.pi)
atan_array *= (180/np.pi)

print (atan_array)

[  0.  15.  30.  45.  60.  75.  90.]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [7]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
dx = np.diff(x)
print (dx)

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [11]:
read_data = np.loadtxt('sample.txt')
count, edges = np.histogram(read_data)
centers = np.mean(np.stack((edges[:-1] , edges[1:])), axis = 0)
print ('Center of bins: {}'.format(centers))
print ('Counts of each bin: {}'.format(count))

Center of bins: [-24.10900649 -11.1501637    1.80867908  14.76752187  27.72636466
  40.68520745  53.64405024  66.60289303  79.56173582  92.52057861]
Counts of each bin: [ 6 23 52 37 16 14 13 13 13 13]


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:
$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [10]:
cc = np.random.random_sample((1, 10))
mean_cc = np.mean(cc)
sqr_dev = (cc - mean_cc)**2
avg_dev = np.sum(sqr_dev)/np.shape(cc)[1]
cc_std = np.sqrt(avg_dev)
py_std = np.std(cc)

print ('Programmed STD: {}'.format(cc_std))
print ('Numpy STD : {}'.format(py_std))

Programmed STD: 0.2721746538717936
Numpy STD : 0.2721746538717936
