In [2]:
import numpy as np

## Q. 1
We can use np.random.random_sample() to create an array with random values. By default, these will be in the range [0.0, 1.0). You can multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, np.mean()).

In [3]:
rand_array = np.random.random_sample((10, 10))
rand_range = 10*rand_array + 0        # random array of elements between 0  and 10
array_mean = np.mean(rand_range)
print ('Mean of array elements: {}'.format(array_mean))

Mean of array elements: 4.892923053267248


## Q. 2
Create the array:

[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [9]:
nrows = 5
ncols = 3
old_array = np.arange(1, 16, 1).reshape(ncols, nrows)
modified_array = old_array.T
new_array = modified_array[1:4:2, :]
print (new_array)

[[ 2  7 12]
 [ 4  9 14]]


# Q. 3
Create a 2d array with 1 on the border and 0 on the inside, e.g., like:

1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
Do this using array slice notation to let it work for an arbitrary-sized array

In [18]:
nrows = 4
ncols = 5
array_1 = np.ones((nrows, ncols))
array_2 = array_1
array_2[1:nrows-1, 1:ncols-1] = 0
print (array_2)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [28]:
stride_val = 15
ang_array = np.arange(0, 90+stride_val, stride_val)
ang_array2 = (np.pi/180)*ang_array
sine_array = np.sin(ang_array2)
cosine_array = np.sin(ang_array2)
tangent_array = np.tan(ang_array2)
# Compute inverses
asin_array = np.arcsin(sine_array)
acos_array = np.arccos(cosine_array)
atan_array = np.arctan(tangent_array)

asin_array *= (180/np.pi)
acos_array *= (180/np.pi)
atan_array *= (180/np.pi)

print (atan_array)

[  0.  15.  30.  45.  60.  75.  90.]


# Q 5

In [29]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
dx = np.diff(x)
print (dx)

[-2  3  3  3 -4  6  2 -9]


# Q 6

In [51]:
read_data = np.loadtxt('sample.txt')
count, edges = np.histogram(read_data)
centers = np.mean(np.stack((edges[:-1] , edges[1:])), axis = 0)
print ('Center of bins: {}'.format(centers))
print ('Counts of each bin: {}'.format(count))

Center of bins: [-24.10900649 -11.1501637    1.80867908  14.76752187  27.72636466
  40.68520745  53.64405024  66.60289303  79.56173582  92.52057861]
Counts of each bin: [ 6 23 52 37 16 14 13 13 13 13]


# Q 7

In [59]:
cc = np.random.random_sample((1, 10))
mean_cc = np.mean(cc)
sqr_dev = (cc - mean_cc)**2
avg_dev = np.sum(sqr_dev)/np.shape(cc)[1]
cc_std = np.sqrt(avg_dev)
py_std = np.std(cc)

print ('Programmed STD: {}'.format(cc_std))
print ('Numpy STD : {}'.format(py_std))

Programmed STD: 0.24476594882409486
Numpy STD : 0.24476594882409486
